### ISSUE TITLE
Document the GL/GLES/bpp requirements?

### ISSUE THREAD

**Issue by MagaTailor** [polydraw/polydraw#7] opened 2016-06-16 00:18 UTC
Trying to run an example fails like this on a GLES 2.0 ARM Linux system @ 24bpp:

``` shell
  Running `target/release/examples/arcs`
thread 'main' panicked at 'eglBindAPI failed', src/application.rs:45
```

The README doesn't mention any special requirements though.

**Comment by majorz** [comment] 2016-06-16 13:00
Good point. I will add the info about what platforms the demos are currently working on.

**Comment by majorz** [comment] 2016-06-16 20:25
It is done now. I added a table with currently supported combinations of operating systems and GPU platforms.

**Comment by petevine** [comment] 2016-06-16 20:42
Thanks!

**Comment by MagaTailor** [comment] 2016-06-16 20:48
Thanks! Minimum required GL versions would be nice, though - not everyone knows popular rust libs default to 3.3.

**Comment by majorz** [comment] 2016-06-16 21:07
Good idea, reopening the ticket. I will install some older distros on VMs and make sure I report things correctly in terms of GL version requirements.

I did custom bindings for GL, where older GL functions are linked directly and newer ones are queried with `eglGetProcAddress/wglGetProcAddress`.

For fast access to the GPU I am using functions like `glBlitFramebuffer` - those are truly making a difference. However if there are people who have a lesser GL versions on their system, I can get it working on older GL APIs as well if the new ones are not available.

**Comment by MagaTailor** [comment] 2016-06-16 21:11
That would be great! For example, on my odroid I've got accelerated OpenGL `1.5` via [glshim](https://github.com/ptitSeb/glshim), soft Mesa OpenGL 2.0 and hardware OpenGL ES 1.1/2.0 via the binary only Mali driver.

**Comment by MagaTailor** [comment] 2016-06-16 21:14
Other interesting tidbit - the popular Raspberry Pi boards recently got hardware OpenGL 2.0 support (like a couple of months ago, prieviously only GLES 2.0).

**Comment by majorz** [comment] 2016-06-16 21:19
Right, so support of older GL versions is a must, since some of those new APIs require GLES 3.0. The good news is that I already did a previous implementation with the older APIs, so I will dig it up from the git history and figure out some way to fallback gracefully to it.

**Comment by MagaTailor** [comment] 2016-06-16 21:23
Thx, I'm looking forward to some testing! :)

**Comment by majorz** [comment] 2016-06-16 21:24
Thanks for the support :D

**Comment by majorz** [comment] 2016-06-27 10:46
Some progress report here.

I implemented the GLX support for Linux, so now both EGL and GLX are supported (GLX was needed for some proprietary drivers that did not supported EGL, not for the ARM support).

Over the weekend I installed latest Raspbian on top of QEMU, since I do not have the real hardware yet. So support for older GL versions is coming next :)

**Comment by MagaTailor** [comment] 2016-06-27 12:04
Yup! Software MESA Open GL 2.0 works fine. How can I make the examples use GLES 2.0?

**Comment by majorz** [comment] 2016-06-27 14:49
I have been thinking over this and I will make a small info tool, which will query the GL/GLES device capabilities. I will start working on this today.

I use eglBindAPI, which now is hardcoded to use GL, not GLES here:
https://github.com/polydraw/polydraw/blob/bed51bd0ecf58c72ef335960e982f1f6f7e0b79e/src/os/linux/context/egl.rs#L52

I am not sure if that would work, but if you change this line from `egl::bind_api(egl::API::OpenGL)` to `egl::bind_api(egl::API::OpenGLES)`, maybe that will have an effect. If not, the info tool will help to see where we are falling short.

**Comment by MagaTailor** [comment] 2016-06-27 15:20
Strangely, the code compiles but the change is ineffective (runs using OpenGL).

**Comment by majorz** [comment] 2016-06-27 17:09
Thanks for checking! I think the info tool will provide enough diagnostic to determine the issue. I will follow up very soon on the development.

**Comment by majorz** [comment] 2016-06-29 11:09
I investigated the matter further those couple of days. I saw the mesa demo tools either link to libGL.so (like glxgears) or to libGLESv2.so (like es2gears). Right now I statically link to GL. One way to solve this is by default target by architecture with additional option to overwrite it by configuration - I need to check how others are approaching this. Another option would be to implement runtime loading - very similar to how dynamic languages approach it, however I will have to check for drawbacks.

I did some local modifications to try to run with GLES on my Ubuntu laptop, but I have a problem with glMapBuffer that I need to solve first. It is looking promising though and I will follow up soon on that.

Another thing I found when I was working with Raspian in QEMU is that there are problems with the virtualization of the GPU and I cannot run almost any GL app there - even the ones with software rasterization, not mentioning the hardware accelerated implementation. So I need to grab some real hardware as soon as possible :)

**Comment by MagaTailor** [comment] 2016-06-29 13:27
No worries, I'll test it for you on my SBC!

**Comment by majorz** [comment] 2016-07-03 19:02
Good news here - GLES implementation is now working in a new `gles` branch. Before I merge it to `master` I will need to clean it up and make the linking to GL or GLES configurable, but what is on the `gles` branch should be fine for running the demos. Fingers crossed it will be running without any issues on your hardware.

**Comment by majorz** [comment] 2016-07-03 19:51
I now found on my emulated Raspbian that the EGL attributes are not accepted and I will need to push a few more modifications to make it work there. I will post a bit later a new comment when I fix it.

**Comment by MagaTailor** [comment] 2016-07-03 20:45
On Sun, 03 Jul 2016 12:51:25 -0700
Zahari Petkov notifications@github.com wrote:

> I will post a bit later a new comment when I fix it.

Great, I'll try it out tonight. In the future I'd love to see glshim used by rust code for the first time (OpenGL 1.5).

**Comment by majorz** [comment] 2016-07-03 22:36
I pushed the fixes that makes the demos run (e.g. `cargo run --example arcs --release`). However I get some final texture display banding issue on my emulated environment. Please let me know if it is displaying properly for you when you have some free time to check it out.

I am thinking about using a more dynamic loading for the future and avoid static linking altogether. Like that I should be able to support not only older GL version more easier, but also larger set of windowing systems. Also the compilation process will be less complicated, since it will not need installed dev packages.

**Comment by MagaTailor** [comment] 2016-07-03 22:41
Yeah, that's how I always ran the examples when they defaulted to GL. How do I make the examples use GLES?

**Comment by majorz** [comment] 2016-07-03 22:47
The `gles` branch now links to GLES (libGLESv2.so) instead of GL, so now it defaults to GLES instead of GL.

When I merge with `master` I will add an environment variable to configure the choice between both when building.

**Comment by MagaTailor** [comment] 2016-07-03 22:51
Ah, sorry, forgot about the new branch! But, at least I've just discovered master examples don't run on my  system any more. Let's close this issue and move to separate GL/GLES issues. (if necessary)

**Closed as completed** 2016-07-03 22:54 UTC

**Comment by majorz** [comment] 2016-07-03 23:00
Thanks, I created a new GLES issue to track the current progress there. If you see an error in the terminal when running the code on `master`, can you please create an issue for that. I will try to reproduce now as well.
